ADVANCED_MAP = {
    "accountId": "accountId",
    "acctAlias": "acctAlias",
    "currency": "currency",
    "levelOfDetail": "levelOfDetail",
    "endingCash": "endingCash",
    "startingCash": "startingCash",
    "deposits": "deposits",
    "withdrawals": "withdrawals",
    "netTradesSales": "netTradesSales",
    "netTradesPurchases": "netTradesPurchases",
    "dividends": "dividends",
    "brokerInterest": "brokerInterest",
    "brokerFees": "brokerFees",
    "transactionTax": "transactionTax",
    "withholdingTax": "withholdingTax",
    "otherFees": "otherFees",
    "otherIncome": "otherIncome",
    "endingSettledCash": "endingSettledCash",
}
